# pull the official base image
FROM node:alpine

# set working direction
WORKDIR /app
# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install application dependencies
COPY ui-web/package.json ./
COPY ui-web/yarn.lock ./

RUN yarn install

# add app
COPY ui-web/ ./

# start app
CMD ["yarn", "start"]